/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2.davidbendeck;

import Usuarios.Cliente;
import Usuarios.Usuario;
import Usuarios.UsuarioMantenimiento;
import java.awt.Dialog;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davidbendeck
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        //Leer usuarios
        leerUsuarios(usuarios);
        
         //Leer ATMs
        leerATMs(atms);
        
        for (ATM atm : atms) {
            CB_ATMs_InicioSesion.addItem(atm);
        }
        
        transRecibo = null;
        ultNumCuenta = leerNumCuenta();
        idTxn = leerIdTxn();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_LogIn = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        LBL_Bienvenida_LogIn = new javax.swing.JLabel();
        TF_ID_LogIn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        PF_Clave_LogIn = new javax.swing.JPasswordField();
        B_IniciarSesion_LogIn = new javax.swing.JButton();
        D_MenuCliente = new javax.swing.JDialog();
        P_MenuCliente = new javax.swing.JPanel();
        B_NuevaCuenta = new javax.swing.JButton();
        B_EstadoCuenta = new javax.swing.JButton();
        B_Transacciones = new javax.swing.JButton();
        B_RetiroPropias = new javax.swing.JButton();
        B_DepositoPropias = new javax.swing.JButton();
        B_DepositoTerceros = new javax.swing.JButton();
        D_MenuMantenimiento = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TF_Billetes500_Mantenimiento = new javax.swing.JTextField();
        TF_Billetes100_Mantenimiento = new javax.swing.JTextField();
        B_Finalizar_Mantenimiento = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        D_Confirmacion = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        B_Confirmar_Confirmacion = new javax.swing.JButton();
        LBL_Pass_Confirmacion = new javax.swing.JLabel();
        PF_Clave_Confirmacion = new javax.swing.JPasswordField();
        D_RetiroPropias = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        CB_Cuentas_RetiroPropia = new javax.swing.JComboBox<>();
        TF_Monto_RetiroPropia = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        B_Retirar_RetiroPropia = new javax.swing.JButton();
        D_DepositoPropias = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        TF_Monto_DepositarPropia = new javax.swing.JTextField();
        CB_Cuentas_DepositoPropia = new javax.swing.JComboBox<>();
        B_Depositar_DepositarPropia = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        D_DepositoTerceros = new javax.swing.JDialog();
        jLabel31 = new javax.swing.JLabel();
        TF_Monto_DepositoTerceros = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        CB_Cuentas_DepositoTerceros = new javax.swing.JComboBox<>();
        B_Depositar_DepositoTerceros = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        D_NuevaCuenta = new javax.swing.JDialog();
        D_EstadoCuenta = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        CB_Cuentas_EstadoCuenta = new javax.swing.JComboBox<>();
        B_RevisarEstado_EstadoCuenta = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        D_Transacciones = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBL_Transacciones = new javax.swing.JTable();
        B_Salir_Transacciones = new javax.swing.JButton();
        TP_Principal = new javax.swing.JTabbedPane();
        P_InicioSesion = new javax.swing.JPanel();
        CB_ATMs_InicioSesion = new javax.swing.JComboBox<>();
        B_EscojerATM = new javax.swing.JButton();
        P_Usuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_ID_CrearUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_Nombre1_CrearUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_Nombre2_CrearUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_Apellido1_CrearUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF_Apellido2_CrearUsuario = new javax.swing.JTextField();
        PF_Clave_CrearUsuario = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_Nacimiento_CrearUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF_Afiliacion_CrearUsuario = new javax.swing.JTextField();
        B_CrearUsuario = new javax.swing.JButton();
        CB_TipoUsuario_CrearUsuario = new javax.swing.JComboBox<>();
        P_ATM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TF_ID_CrearATM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_Ubicacion_CrearATM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TF_Fabricacion_CrearATM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TF_Mantenimiento_CrearATM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_Billetes100_CrearATM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TF_Billetes500_CrearATM = new javax.swing.JTextField();
        B_CrearATM_CrearATMs = new javax.swing.JButton();
        P_AsignarATMs = new javax.swing.JPanel();
        CB_ATMs_AsignarATMs = new javax.swing.JComboBox<>();
        B_Asignar_AsignarATMs = new javax.swing.JButton();
        CB_UsuarioMantenimiento_AsignarATMs = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        jLabel19.setText("ID");

        LBL_Bienvenida_LogIn.setText("Bienvenida");

        jLabel20.setText("Clave");

        B_IniciarSesion_LogIn.setText("Iniciar Sesión");
        B_IniciarSesion_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_IniciarSesion_LogInMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout D_LogInLayout = new javax.swing.GroupLayout(D_LogIn.getContentPane());
        D_LogIn.getContentPane().setLayout(D_LogInLayout);
        D_LogInLayout.setHorizontalGroup(
            D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_LogInLayout.createSequentialGroup()
                .addGroup(D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(D_LogInLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(LBL_Bienvenida_LogIn))
                    .addGroup(D_LogInLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(93, 93, 93)
                        .addGroup(D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_ID_LogIn)
                            .addComponent(PF_Clave_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                    .addGroup(D_LogInLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(B_IniciarSesion_LogIn)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        D_LogInLayout.setVerticalGroup(
            D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_LogInLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(LBL_Bienvenida_LogIn)
                .addGap(85, 85, 85)
                .addGroup(D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TF_ID_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(D_LogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(PF_Clave_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(B_IniciarSesion_LogIn)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        B_NuevaCuenta.setText("Crear Nueva Cuenta");
        B_NuevaCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_NuevaCuentaMouseClicked(evt);
            }
        });

        B_EstadoCuenta.setText("Revisar Estado de Cuenta");
        B_EstadoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_EstadoCuentaMouseClicked(evt);
            }
        });

        B_Transacciones.setText("Revisar Transacciones");
        B_Transacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_TransaccionesMouseClicked(evt);
            }
        });

        B_RetiroPropias.setText("Retiro Cuentas Propias");
        B_RetiroPropias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_RetiroPropiasMouseClicked(evt);
            }
        });

        B_DepositoPropias.setText("Deposito Cuentas Propias");
        B_DepositoPropias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_DepositoPropiasMouseClicked(evt);
            }
        });

        B_DepositoTerceros.setText("Deposito Cuenta Terceros");
        B_DepositoTerceros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_DepositoTercerosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_MenuClienteLayout = new javax.swing.GroupLayout(P_MenuCliente);
        P_MenuCliente.setLayout(P_MenuClienteLayout);
        P_MenuClienteLayout.setHorizontalGroup(
            P_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_MenuClienteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(P_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_MenuClienteLayout.createSequentialGroup()
                        .addComponent(B_DepositoTerceros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_Transacciones))
                    .addGroup(P_MenuClienteLayout.createSequentialGroup()
                        .addComponent(B_DepositoPropias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                        .addComponent(B_EstadoCuenta))
                    .addGroup(P_MenuClienteLayout.createSequentialGroup()
                        .addComponent(B_RetiroPropias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_NuevaCuenta)))
                .addGap(68, 68, 68))
        );
        P_MenuClienteLayout.setVerticalGroup(
            P_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MenuClienteLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(P_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_NuevaCuenta)
                    .addComponent(B_RetiroPropias))
                .addGap(76, 76, 76)
                .addGroup(P_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_EstadoCuenta)
                    .addComponent(B_DepositoPropias))
                .addGap(83, 83, 83)
                .addGroup(P_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Transacciones)
                    .addComponent(B_DepositoTerceros))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_MenuClienteLayout = new javax.swing.GroupLayout(D_MenuCliente.getContentPane());
        D_MenuCliente.getContentPane().setLayout(D_MenuClienteLayout);
        D_MenuClienteLayout.setHorizontalGroup(
            D_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_MenuClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_MenuCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        D_MenuClienteLayout.setVerticalGroup(
            D_MenuClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_MenuClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(P_MenuCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel21.setText("Numero de billetes de 100 ingresados");

        jLabel22.setText("Numero de billetes de 500 ingresados");

        B_Finalizar_Mantenimiento.setText("Finalizar mantenimiento");
        B_Finalizar_Mantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Finalizar_MantenimientoMouseClicked(evt);
            }
        });

        jLabel23.setText("Mantenimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_Billetes100_Mantenimiento)
                            .addComponent(TF_Billetes500_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(B_Finalizar_Mantenimiento)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel23)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TF_Billetes100_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Billetes500_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(B_Finalizar_Mantenimiento)
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout D_MenuMantenimientoLayout = new javax.swing.GroupLayout(D_MenuMantenimiento.getContentPane());
        D_MenuMantenimiento.getContentPane().setLayout(D_MenuMantenimientoLayout);
        D_MenuMantenimientoLayout.setHorizontalGroup(
            D_MenuMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_MenuMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_MenuMantenimientoLayout.setVerticalGroup(
            D_MenuMantenimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_MenuMantenimientoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setText("Ingrese su clave para confirmar su accion");

        jLabel25.setText("Clave");

        B_Confirmar_Confirmacion.setText("Confirmar accion");
        B_Confirmar_Confirmacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Confirmar_ConfirmacionMouseClicked(evt);
            }
        });

        LBL_Pass_Confirmacion.setText("pass");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel24))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel25)
                        .addGap(66, 66, 66)
                        .addComponent(PF_Clave_Confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Confirmar_Confirmacion)
                .addGap(88, 88, 88)
                .addComponent(LBL_Pass_Confirmacion)
                .addGap(77, 77, 77))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel24)
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(PF_Clave_Confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Confirmar_Confirmacion)
                    .addComponent(LBL_Pass_Confirmacion))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout D_ConfirmacionLayout = new javax.swing.GroupLayout(D_Confirmacion.getContentPane());
        D_Confirmacion.getContentPane().setLayout(D_ConfirmacionLayout);
        D_ConfirmacionLayout.setHorizontalGroup(
            D_ConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_ConfirmacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_ConfirmacionLayout.setVerticalGroup(
            D_ConfirmacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_ConfirmacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel30.setText("Cuenta");

        jLabel29.setText("Monto a retirar");

        B_Retirar_RetiroPropia.setText("Retirar dinero");
        B_Retirar_RetiroPropia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Retirar_RetiroPropiaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TF_Monto_RetiroPropia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(129, 129, 129)
                        .addComponent(CB_Cuentas_RetiroPropia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(B_Retirar_RetiroPropia)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(CB_Cuentas_RetiroPropia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Monto_RetiroPropia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(77, 77, 77)
                .addComponent(B_Retirar_RetiroPropia)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_RetiroPropiasLayout = new javax.swing.GroupLayout(D_RetiroPropias.getContentPane());
        D_RetiroPropias.getContentPane().setLayout(D_RetiroPropiasLayout);
        D_RetiroPropiasLayout.setHorizontalGroup(
            D_RetiroPropiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_RetiroPropiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_RetiroPropiasLayout.setVerticalGroup(
            D_RetiroPropiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel26.setText("Monto");

        B_Depositar_DepositarPropia.setText("Depositar");
        B_Depositar_DepositarPropia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Depositar_DepositarPropiaMouseClicked(evt);
            }
        });

        jLabel27.setText("Cuenta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Depositar_DepositarPropia)
                .addGap(241, 241, 241))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(CB_Cuentas_DepositoPropia, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(81, 81, 81)
                        .addComponent(TF_Monto_DepositarPropia, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_Cuentas_DepositoPropia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(TF_Monto_DepositarPropia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(B_Depositar_DepositarPropia)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout D_DepositoPropiasLayout = new javax.swing.GroupLayout(D_DepositoPropias.getContentPane());
        D_DepositoPropias.getContentPane().setLayout(D_DepositoPropiasLayout);
        D_DepositoPropiasLayout.setHorizontalGroup(
            D_DepositoPropiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_DepositoPropiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_DepositoPropiasLayout.setVerticalGroup(
            D_DepositoPropiasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_DepositoPropiasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel31.setText("Cuenta");

        jLabel32.setText("Monto");

        B_Depositar_DepositoTerceros.setText("Efectuar deposito");
        B_Depositar_DepositoTerceros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Depositar_DepositoTercerosMouseClicked(evt);
            }
        });

        jLabel33.setText("Deposito a terceros");

        javax.swing.GroupLayout D_DepositoTercerosLayout = new javax.swing.GroupLayout(D_DepositoTerceros.getContentPane());
        D_DepositoTerceros.getContentPane().setLayout(D_DepositoTercerosLayout);
        D_DepositoTercerosLayout.setHorizontalGroup(
            D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_DepositoTercerosLayout.createSequentialGroup()
                .addGroup(D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(D_DepositoTercerosLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel31))
                        .addGap(82, 82, 82)
                        .addGroup(D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_Monto_DepositoTerceros)
                            .addComponent(CB_Cuentas_DepositoTerceros, 0, 192, Short.MAX_VALUE)))
                    .addGroup(D_DepositoTercerosLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(B_Depositar_DepositoTerceros))
                    .addGroup(D_DepositoTercerosLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel33)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        D_DepositoTercerosLayout.setVerticalGroup(
            D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_DepositoTercerosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel33)
                .addGap(63, 63, 63)
                .addGroup(D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(CB_Cuentas_DepositoTerceros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(D_DepositoTercerosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Monto_DepositoTerceros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(B_Depositar_DepositoTerceros)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout D_NuevaCuentaLayout = new javax.swing.GroupLayout(D_NuevaCuenta.getContentPane());
        D_NuevaCuenta.getContentPane().setLayout(D_NuevaCuentaLayout);
        D_NuevaCuentaLayout.setHorizontalGroup(
            D_NuevaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        D_NuevaCuentaLayout.setVerticalGroup(
            D_NuevaCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        B_RevisarEstado_EstadoCuenta.setText("Revisar estado");
        B_RevisarEstado_EstadoCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_RevisarEstado_EstadoCuentaMouseClicked(evt);
            }
        });

        jLabel28.setText("Cuenta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel28))
                    .addComponent(CB_Cuentas_EstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(B_RevisarEstado_EstadoCuenta)))
                .addGap(180, 180, 180))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel28)
                .addGap(31, 31, 31)
                .addComponent(CB_Cuentas_EstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(B_RevisarEstado_EstadoCuenta)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_EstadoCuentaLayout = new javax.swing.GroupLayout(D_EstadoCuenta.getContentPane());
        D_EstadoCuenta.getContentPane().setLayout(D_EstadoCuentaLayout);
        D_EstadoCuentaLayout.setHorizontalGroup(
            D_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_EstadoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_EstadoCuentaLayout.setVerticalGroup(
            D_EstadoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_EstadoCuentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        TBL_Transacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Cuenta", "Descripcion", "Fecha y hora", "ID transaccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TBL_Transacciones);

        B_Salir_Transacciones.setText("Salir");
        B_Salir_Transacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Salir_TransaccionesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(B_Salir_Transacciones)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(B_Salir_Transacciones)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout D_TransaccionesLayout = new javax.swing.GroupLayout(D_Transacciones.getContentPane());
        D_Transacciones.getContentPane().setLayout(D_TransaccionesLayout);
        D_TransaccionesLayout.setHorizontalGroup(
            D_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, D_TransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        D_TransaccionesLayout.setVerticalGroup(
            D_TransaccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(D_TransaccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TP_Principal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TP_PrincipalStateChanged(evt);
            }
        });

        B_EscojerATM.setText("Escojer ATM");
        B_EscojerATM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_EscojerATMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_InicioSesionLayout = new javax.swing.GroupLayout(P_InicioSesion);
        P_InicioSesion.setLayout(P_InicioSesionLayout);
        P_InicioSesionLayout.setHorizontalGroup(
            P_InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_InicioSesionLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addGroup(P_InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_InicioSesionLayout.createSequentialGroup()
                        .addComponent(CB_ATMs_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_InicioSesionLayout.createSequentialGroup()
                        .addComponent(B_EscojerATM)
                        .addGap(324, 324, 324))))
        );
        P_InicioSesionLayout.setVerticalGroup(
            P_InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_InicioSesionLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(CB_ATMs_InicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(B_EscojerATM)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Inicio de Sesión", P_InicioSesion);

        jLabel1.setText("ID:");

        jLabel2.setText("Primer nombre");

        jLabel3.setText("Segundo nombre");

        jLabel4.setText("Primer apellido");

        jLabel5.setText("Segundo apellido");

        jLabel6.setText("Clave");

        jLabel7.setText("Año de nacimiento");

        jLabel8.setText("Año de afiliación");

        B_CrearUsuario.setText("Crear Usuario");
        B_CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearUsuarioMouseClicked(evt);
            }
        });

        CB_TipoUsuario_CrearUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario Cliente", "Usuario Mantenimiento" }));

        javax.swing.GroupLayout P_UsuarioLayout = new javax.swing.GroupLayout(P_Usuario);
        P_Usuario.setLayout(P_UsuarioLayout);
        P_UsuarioLayout.setHorizontalGroup(
            P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_UsuarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(56, 56, 56)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PF_Clave_CrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(TF_Apellido1_CrearUsuario)
                    .addComponent(TF_Apellido2_CrearUsuario)
                    .addComponent(TF_Nacimiento_CrearUsuario)
                    .addComponent(TF_Afiliacion_CrearUsuario)
                    .addComponent(TF_Nombre1_CrearUsuario)
                    .addComponent(TF_Nombre2_CrearUsuario)
                    .addComponent(TF_ID_CrearUsuario))
                .addGap(90, 90, 90)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_CrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB_TipoUsuario_CrearUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        P_UsuarioLayout.setVerticalGroup(
            P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_UsuarioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_ID_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_UsuarioLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_Nombre1_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_UsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_TipoUsuario_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_Nombre2_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_UsuarioLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TF_Apellido1_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TF_Apellido2_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P_UsuarioLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(B_CrearUsuario)))
                .addGap(27, 27, 27)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PF_Clave_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TF_Nacimiento_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_Afiliacion_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Crear Usuario", P_Usuario);

        jLabel9.setText("ID");

        jLabel10.setText("Ubicacion");

        jLabel11.setText("Año de fabricación");

        jLabel12.setText("Periodo entre mantenimientos (dias)");

        jLabel14.setText("Billetes de 100");

        jLabel13.setText("Billetes de 500");

        B_CrearATM_CrearATMs.setText("Crear ATM");
        B_CrearATM_CrearATMs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearATM_CrearATMsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout P_ATMLayout = new javax.swing.GroupLayout(P_ATM);
        P_ATM.setLayout(P_ATMLayout);
        P_ATMLayout.setHorizontalGroup(
            P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ATMLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ATMLayout.createSequentialGroup()
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(P_ATMLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(TF_Mantenimiento_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, P_ATMLayout.createSequentialGroup()
                                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(103, 103, 103)
                                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Billetes100_CrearATM)
                                    .addComponent(TF_Billetes500_CrearATM))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(P_ATMLayout.createSequentialGroup()
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(74, 74, 74)
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_ID_CrearATM, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(TF_Ubicacion_CrearATM)
                            .addComponent(TF_Fabricacion_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(B_CrearATM_CrearATMs)
                        .addGap(106, 106, 106))))
        );
        P_ATMLayout.setVerticalGroup(
            P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ATMLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_ID_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TF_Ubicacion_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ATMLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TF_Fabricacion_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_ATMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B_CrearATM_CrearATMs)
                        .addGap(25, 25, 25)))
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TF_Mantenimiento_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TF_Billetes100_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TF_Billetes500_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Crear ATM", P_ATM);

        B_Asignar_AsignarATMs.setText("Asignar ");
        B_Asignar_AsignarATMs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_Asignar_AsignarATMsMouseClicked(evt);
            }
        });

        jLabel15.setText("ATM");

        jLabel16.setText("Asignar a");

        jLabel17.setText("------>");

        jLabel18.setText("Usuario de Mantenimiento");

        javax.swing.GroupLayout P_AsignarATMsLayout = new javax.swing.GroupLayout(P_AsignarATMs);
        P_AsignarATMs.setLayout(P_AsignarATMsLayout);
        P_AsignarATMsLayout.setHorizontalGroup(
            P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(253, 253, 253)
                        .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(jLabel18))))
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addComponent(CB_ATMs_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CB_UsuarioMantenimiento_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(B_Asignar_AsignarATMs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_AsignarATMsLayout.setVerticalGroup(
            P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)))
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_ATMs_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_UsuarioMantenimiento_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(B_Asignar_AsignarATMs)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Asignar ATMs", P_AsignarATMs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearUsuarioMouseClicked
        // TODO add your handling code here:
        
        String ID = TF_ID_CrearUsuario.getText();
        String nombre1 = TF_Nombre1_CrearUsuario.getText();
        String nombre2 = TF_Nombre2_CrearUsuario.getText();
        String apellido1 = TF_Apellido1_CrearUsuario.getText();
        String apellido2 = TF_Apellido2_CrearUsuario.getText();
        String clave = PF_Clave_CrearUsuario.getText();
        int nacimiento = Integer.parseInt(TF_Nacimiento_CrearUsuario.getText());
        int afiliacion = Integer.parseInt(TF_Afiliacion_CrearUsuario.getText());
        
        for (Usuario usuario : usuarios) {
            if (usuario.getId().equals(ID)) {
                JOptionPane.showMessageDialog(this, "Este ID ya existe");
                return;
            }
        }
        
        String tipoUsuario = (String) CB_TipoUsuario_CrearUsuario.getSelectedItem();
        if (tipoUsuario.equals("Usuario Cliente")) {
            usuarios.add(new Cliente(new ArrayList<Cuenta>(), new ArrayList<Transaccion>(), ID, nombre1, nombre2, apellido1, apellido2, clave, nacimiento, afiliacion));
        } else {
            usuarios.add(new UsuarioMantenimiento(new ArrayList<String>(), ID, nombre1, nombre2, apellido1, apellido2, clave, nacimiento, afiliacion));
        }
        
        guardarUsuarios(usuarios);
        JOptionPane.showMessageDialog(this, "Se ha creado un nuevo usuario con exito");
    }//GEN-LAST:event_B_CrearUsuarioMouseClicked

    private void B_CrearATM_CrearATMsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearATM_CrearATMsMouseClicked
        // TODO add your handling code here:
        
        String ID = TF_ID_CrearATM.getText();
        String ubicacion = TF_Ubicacion_CrearATM.getText();
        int fabricacion = Integer.parseInt(TF_Fabricacion_CrearATM.getText());
        int mantenimiento = Integer.parseInt(TF_Mantenimiento_CrearATM.getText());
        int billetes100 = Integer.parseInt(TF_Billetes100_CrearATM.getText());
        int billetes500 = Integer.parseInt(TF_Billetes500_CrearATM.getText());
        
        if (ID == null) {
            JOptionPane.showMessageDialog(this, "Escriba un ID valido por favor");
        }
        
        for (ATM atm : atms) {
            if (atm.getAtmId().equals(ID)) {
                JOptionPane.showMessageDialog(this, "Este ID ya existe");
            }
        }
        
        atms.add(new ATM(ID, ubicacion, fabricacion, mantenimiento, billetes100, billetes500));
        guardarATMs(atms);
        
        JOptionPane.showMessageDialog(this, "ATM guardado exitosamente");
    }//GEN-LAST:event_B_CrearATM_CrearATMsMouseClicked

    private void TP_PrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TP_PrincipalStateChanged
        // TODO add your handling code here:
        
        //ATMS ELEGIR
        CB_ATMs_InicioSesion.removeAllItems();
        for (ATM atm : atms) {
            CB_ATMs_InicioSesion.addItem(atm);
        }
        
        //ATMS ASIGNAR
        CB_ATMs_AsignarATMs.removeAllItems();
        for (ATM atm : atms) {
            CB_ATMs_AsignarATMs.addItem(atm);
        }
        
        //USUARIOS MANTENIMIENTO
        CB_UsuarioMantenimiento_AsignarATMs.removeAllItems();
        for (Usuario usuario : usuarios) {
            if (usuario instanceof UsuarioMantenimiento) {
                CB_UsuarioMantenimiento_AsignarATMs.addItem((UsuarioMantenimiento) usuario);
            }
        }
    }//GEN-LAST:event_TP_PrincipalStateChanged

    private void B_Asignar_AsignarATMsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Asignar_AsignarATMsMouseClicked
        // TODO add your handling code here:
        
        UsuarioMantenimiento uMantenimiento = (UsuarioMantenimiento) CB_UsuarioMantenimiento_AsignarATMs.getSelectedItem();
        ATM selectedtAtm = (ATM) CB_ATMs_AsignarATMs.getSelectedItem();
        
        for (String atm : uMantenimiento.getAtms()) {
            if (atm.equals(selectedtAtm.getAtmId())) {
                JOptionPane.showMessageDialog(this, "Este ATM ya ha sido asignado a este usuario de mantenimiento");
                return;
            }
        }
        
        uMantenimiento.getAtms().add(selectedtAtm.getAtmId());
        guardarUsuarios(usuarios);
        
        JOptionPane.showMessageDialog(this, "Se ha asignado el ATM al usuario de mantenimiento");
    }//GEN-LAST:event_B_Asignar_AsignarATMsMouseClicked

    private void B_IniciarSesion_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_IniciarSesion_LogInMouseClicked
        // TODO add your handling code here:
        
        String ID = TF_ID_LogIn.getText();
        String clave = PF_Clave_LogIn.getText();
        Usuario user = null;
        
        for (Usuario usuario : usuarios) {
            if (usuario.getId().equals(ID)) {
                if (usuario.getClave().equals(clave)) {
                    user = usuario;
                }
            }
        }
        if (user == null) {
            contador++;
            if (contador == 5) {
                JOptionPane.showMessageDialog(D_LogIn, "Ha ingresado un ID y/o contraseña incorrecto(s) cinco veces consecutivas");
                guardarLog("ALERTA: Intento fallido de ingreso cinco veces consecutivas, ATM: " + atmActual.getAtmId());
                D_LogIn.setVisible(false);
            }
            JOptionPane.showMessageDialog(D_LogIn, "ID y/o clave incorrecto(s)");
        }
        
        
        else if (user instanceof Cliente) {
            clienteActual = (Cliente) user;
            
            guardarLog("Inicio de sesión, cliente: " + clienteActual.getId() + ", ATM: " + atmActual.getAtmId());
            
            D_LogIn.setVisible(false);
            
            D_MenuCliente.pack();
            D_MenuCliente.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
            D_MenuCliente.setVisible(true);
            
            if (transRecibo != null) {
                int resp = JOptionPane.showConfirmDialog(D_LogIn, "¿Desea imprimir su recibo?");
                
                if (resp == 0) {
                    String factura = "fecha: " + transRecibo.getFechaHora().toString().replace("T", " ").substring(0, 19) + "\n"
                            + "Cajero: " + atmActual.getAtmId() + "\n"
                            + "Ubicacion: " + atmActual.getUbicacion() + "\n"
                            + "Cliente: " + clienteActual.getNombre1() + " " + clienteActual.getApellido1() + "\n"
                            + "\n"
                            + transRecibo.getDescripcion() + "\n\n"
                            + "Gracias por su visita";
                    JOptionPane.showMessageDialog(D_LogIn,factura);
                    transRecibo = null;
                }
            }
        } 
        
        else {
            mantenimientoActual = (UsuarioMantenimiento) user;
            
            if (!mantenimientoActual.getAtms().contains(atmActual.getAtmId())) {
                JOptionPane.showMessageDialog(D_LogIn, "ALERTA: Este ATM no está asignado al usuario de Mantenimiento ingresado");
                guardarLog("Usuario: " + mantenimientoActual + " intentó accesar cajero: " + atmActual + " que no tiene asignado");
                return;
            }
            
            guardarLog("Inicio de sesión, Usuario de mantenimiento: " + mantenimientoActual.getId() + ", ATM: " + atmActual.getAtmId());
            
            D_LogIn.setVisible(false);
            
            D_MenuMantenimiento.pack();
            D_MenuMantenimiento.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
            D_MenuMantenimiento.setVisible(true);
        }
    }//GEN-LAST:event_B_IniciarSesion_LogInMouseClicked

    private void B_EscojerATMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EscojerATMMouseClicked
        // TODO add your handling code here:
        atmActual = (ATM) CB_ATMs_InicioSesion.getSelectedItem();
        
        LBL_Bienvenida_LogIn.setText("Bienvedio al cajero " + atmActual.getUbicacion());
        contador = 0;
        
        D_LogIn.pack();
        D_LogIn.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_LogIn.setVisible(true);
        
        
    }//GEN-LAST:event_B_EscojerATMMouseClicked

    private void B_Finalizar_MantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Finalizar_MantenimientoMouseClicked
        // TODO add your handling code here:
        
        int billetes100 = Integer.parseInt(TF_Billetes100_Mantenimiento.getText());
        int billetes500 = Integer.parseInt(TF_Billetes500_Mantenimiento.getText());
        
        int totalIngresado = billetes100 * 100 + billetes500 * 500;
 
        D_Confirmacion.pack();
        D_Confirmacion.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_Confirmacion.setVisible(true);
        
        if (LBL_Pass_Confirmacion.getText().equals("true")) {
            atmActual.setBilletes100(atmActual.getBilletes100() + billetes100);
            atmActual.setBilletes500(atmActual.getBilletes500() + billetes500);
            JOptionPane.showMessageDialog(D_MenuMantenimiento, "Total ingresado: " + totalIngresado + "\n"
                    + "Total en el cajero: " + (atmActual.getBilletes100() * 100 + atmActual.getBilletes500() * 500) );
            
            guardarLog("Usuario de mantenimiento: " + mantenimientoActual.getId() + " ingresó L." + totalIngresado + " al cajero: " + atmActual.getAtmId()) ;
            
            D_MenuMantenimiento.setVisible(false);
        }
    }//GEN-LAST:event_B_Finalizar_MantenimientoMouseClicked

    private void B_Confirmar_ConfirmacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Confirmar_ConfirmacionMouseClicked
        // TODO add your handling code here:
        
        String clave = PF_Clave_Confirmacion.getText();
        
        if (mantenimientoActual.getClave().equals(clave)) {
            LBL_Pass_Confirmacion.setText("true");
        } else {
            LBL_Pass_Confirmacion.setText("false");
            JOptionPane.showMessageDialog(D_Confirmacion, "Clave incorrecta");
            return;
        }
        
        D_Confirmacion.setVisible(false);
        
    }//GEN-LAST:event_B_Confirmar_ConfirmacionMouseClicked

    private void B_NuevaCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_NuevaCuentaMouseClicked
        // TODO add your handling code here:
        
        ultNumCuenta++;
        guardarNumCuenta(ultNumCuenta);
        idTxn++;
        guardarIdTxn(idTxn);
        
        Cuenta nCuenta = new Cuenta(ultNumCuenta, 0, clienteActual.getId());
        clienteActual.getCuentas().add(nCuenta);
        
        Transaccion nTrans = new Transaccion(ultNumCuenta, "Creación cuenta", LocalDateTime.now(), idTxn);
        transRecibo = nTrans;
        clienteActual.getTransacciones().add(nTrans);
        
        guardarUsuarios(usuarios);
        
        JOptionPane.showMessageDialog(D_MenuCliente, "Nueva cuenta numero: " + ultNumCuenta + " creada");
        
        guardarLog("Creacion cuenta: " + ultNumCuenta + " ,usuario: " + clienteActual + ", ID transaccion: " + idTxn);
        
        D_MenuCliente.setVisible(false);
    }//GEN-LAST:event_B_NuevaCuentaMouseClicked

    private void B_DepositoPropiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_DepositoPropiasMouseClicked
        // TODO add your handling code here:
        
        D_MenuCliente.setVisible(false);
        
        CB_Cuentas_DepositoPropia.removeAllItems();;
        for (Cuenta cuenta : clienteActual.getCuentas()) {
            CB_Cuentas_DepositoPropia.addItem(cuenta);
        }
        
        D_DepositoPropias.pack();
        D_DepositoPropias.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_DepositoPropias.setVisible(true);
        
    }//GEN-LAST:event_B_DepositoPropiasMouseClicked

    private void B_Depositar_DepositarPropiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Depositar_DepositarPropiaMouseClicked
        // TODO add your handling code here:
        idTxn++;
        guardarIdTxn(idTxn);
        
        int monto = Integer.parseInt(TF_Monto_DepositarPropia.getText());
        Cuenta cuenta = (Cuenta) CB_Cuentas_DepositoPropia.getSelectedItem();
        cuenta.setSaldoDisponible(cuenta.getSaldoDisponible() + monto);
        
        Transaccion nTrans = new Transaccion(cuenta.getNumCuenta(), "Deposito de L. " + monto, LocalDateTime.now(), idTxn);
        transRecibo = nTrans;
        clienteActual.getTransacciones().add(nTrans);
        
        guardarUsuarios(usuarios);
        
        JOptionPane.showMessageDialog(D_DepositoPropias, "Deposito exitoso");
        
        
        guardarLog("Cliente: " + clienteActual.getId() + " ha depositado L." + monto + " a la cuenta: " + cuenta.getNumCuenta());
        
        D_DepositoPropias.setVisible(false);
    }//GEN-LAST:event_B_Depositar_DepositarPropiaMouseClicked

    private void B_EstadoCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_EstadoCuentaMouseClicked
        // TODO add your handling code here:
        
        D_MenuCliente.setVisible(false);
        
        CB_Cuentas_EstadoCuenta.removeAllItems();
        for (Cuenta cuenta : clienteActual.getCuentas()) {
            CB_Cuentas_EstadoCuenta.addItem(cuenta);
        }
        
        D_EstadoCuenta.pack();
        D_EstadoCuenta.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_EstadoCuenta.setVisible(true);
        
    }//GEN-LAST:event_B_EstadoCuentaMouseClicked

    private void B_RevisarEstado_EstadoCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RevisarEstado_EstadoCuentaMouseClicked
        // TODO add your handling code here:
        idTxn++;
        guardarIdTxn(idTxn);
        
        Cuenta cuenta = (Cuenta) CB_Cuentas_EstadoCuenta.getSelectedItem();
        Transaccion nTrans = new Transaccion(cuenta.getNumCuenta(), "Revision estado cuenta, cliente: " + clienteActual.getId(), LocalDateTime.now(), idTxn);
        transRecibo = nTrans;
        clienteActual.getTransacciones().add(nTrans);
        
        guardarUsuarios(usuarios);
        
        JOptionPane.showMessageDialog(D_EstadoCuenta, "Numero de cuenta: " + cuenta.getNumCuenta() + ", Saldo: " + cuenta.getSaldoDisponible());
        
        guardarLog("Revision cuenta: " + cuenta.getNumCuenta() + ", saldo: " + cuenta.getSaldoDisponible() + ", usuario: " + clienteActual.getId() + ", transaccion: " + idTxn);
        
        D_EstadoCuenta.setVisible(false);
    }//GEN-LAST:event_B_RevisarEstado_EstadoCuentaMouseClicked

    private void B_TransaccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_TransaccionesMouseClicked
        // TODO add your handling code here:
        
        D_MenuCliente.setVisible(false);
        
        TBL_Transacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Cuenta", "Descripcion", "Fecha y hora", "ID transaccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel tablaTrans = (DefaultTableModel) TBL_Transacciones.getModel();
        for (Transaccion transaccion : clienteActual.getTransacciones()) {
            int numCuenta = transaccion.getNumCuenta();
            String descripcion = transaccion.getDescripcion();
            LocalDateTime fechaHora = transaccion.getFechaHora();
            int txnId = transaccion.getTxnId();
            Object[] newRow = {numCuenta,descripcion,fechaHora,txnId};
            tablaTrans.addRow(newRow);
        }
        
        D_Transacciones.pack();
        D_Transacciones.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_Transacciones.setVisible(true);
    }//GEN-LAST:event_B_TransaccionesMouseClicked

    private void B_Salir_TransaccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Salir_TransaccionesMouseClicked
        // TODO add your handling code here:
        idTxn++;
        guardarIdTxn(idTxn);
       
        Transaccion nTrans = new Transaccion(0, "Revision de transacciones, cliente: " + clienteActual.getId(), LocalDateTime.now(), idTxn);
        transRecibo = nTrans;
        clienteActual.getTransacciones().add(nTrans);
        
        guardarUsuarios(usuarios);
        
        guardarLog("Revision transacciones, usuario: " + clienteActual.getId() + ", transaccion: " + idTxn);
        
        D_Transacciones.setVisible(false);
    }//GEN-LAST:event_B_Salir_TransaccionesMouseClicked

    private void B_RetiroPropiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_RetiroPropiasMouseClicked
        // TODO add your handling code here:
        
        D_MenuCliente.setVisible(false);
        
        CB_Cuentas_RetiroPropia.removeAllItems();
        for (Cuenta cuenta : clienteActual.getCuentas()) {
            CB_Cuentas_RetiroPropia.addItem(cuenta);
        }
        
        D_RetiroPropias.pack();
        D_RetiroPropias.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_RetiroPropias.setVisible(true);
    }//GEN-LAST:event_B_RetiroPropiasMouseClicked

    private void B_Retirar_RetiroPropiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Retirar_RetiroPropiaMouseClicked
        // TODO add your handling code here:
        
        Cuenta cuenta = (Cuenta) CB_Cuentas_RetiroPropia.getSelectedItem();
        int monto = Integer.parseInt(TF_Monto_RetiroPropia.getText());
        
        if (!(monto % 100 == 0)) {
            JOptionPane.showMessageDialog(D_RetiroPropias, "El monto debe de ser multiplo de 100");
            return;
        }
        
        if (cuenta.getSaldoDisponible() < monto) {
            JOptionPane.showMessageDialog(D_RetiroPropias, "Su saldo es insuficiente");
            return;
        }
        
        int dineroATM = atmActual.getBilletes100() * 100 + atmActual.getBilletes500() * 500;
        if (dineroATM < monto) {
            JOptionPane.showMessageDialog(D_RetiroPropias, "Este cajero no tiene suficiente dinero");
            guardarLog("Retiro cancelado por dinero insuficiente en cajero, cliente: " + clienteActual.getId() + ", monto: " + monto);
            D_RetiroPropias.setVisible(false);
            return;
        }
        
        int n500 = Math.min(atmActual.getBilletes500(), monto/500);
        
        int n100 = Math.max(atmActual.getBilletes100(), (monto - n500 * 500)/100);
        
        System.out.println("n500: " + n500);
        System.out.println("n100: " + n100);
        System.out.println("Cajero b500: " + atmActual.getBilletes500());
        System.out.println("Cajero b100: " + atmActual.getBilletes100());
        if ((n500 * 500 + n100 * 100) != monto) {
            JOptionPane.showMessageDialog(D_RetiroPropias, "Retiro cancelado, No hay suficientes billetes de 100 para el monto solicitado");
            guardarLog("Retiro cancelado por dinero insuficiente en cajero, cliente: " + clienteActual.getId() + ", monto: " + monto);
            D_RetiroPropias.setVisible(false);
            return;
        }
        
        idTxn++;
        guardarIdTxn(idTxn);
        
        Transaccion nTrans = new Transaccion(cuenta.getNumCuenta(),"Retiro de L." + monto, LocalDateTime.now(),idTxn);
        transRecibo = nTrans;
        clienteActual.getTransacciones().add(nTrans);
        cuenta.setSaldoDisponible(cuenta.getSaldoDisponible() - monto);
        guardarUsuarios(usuarios);
        
        atmActual.setBilletes500(atmActual.getBilletes500() - n500);
        atmActual.setBilletes100(atmActual.getBilletes100() - n100);
        guardarATMs(atms);
        
        guardarLog("Retiro de L." + monto + ", cuenta: " + cuenta.getNumCuenta() + ", cliente: " + clienteActual.getId() + ", Transaccion: " + idTxn);
        
        JOptionPane.showMessageDialog(D_RetiroPropias, "Retiro exitoso");
        
        D_RetiroPropias.setVisible(false);

    }//GEN-LAST:event_B_Retirar_RetiroPropiaMouseClicked

    private void B_DepositoTercerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_DepositoTercerosMouseClicked
        // TODO add your handling code here:
        D_MenuCliente.setVisible(false);
        
        CB_Cuentas_DepositoTerceros.removeAllItems();
        for (Usuario usuario : usuarios) {
            if (usuario instanceof Cliente) {
                if (!usuario.equals(clienteActual)) {
                    for (Cuenta cuenta : ((Cliente) usuario).getCuentas()) {
                        CB_Cuentas_DepositoTerceros.addItem(cuenta);
                        
                    }
                }
            }
        }
        
        D_DepositoTerceros.pack();
        D_DepositoTerceros.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        D_DepositoTerceros.setVisible(true);
        
    }//GEN-LAST:event_B_DepositoTercerosMouseClicked

    private void B_Depositar_DepositoTercerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Depositar_DepositoTercerosMouseClicked
        // TODO add your handling code here:
        idTxn++;
        guardarIdTxn(idTxn);
        
        Cuenta cuenta = (Cuenta) CB_Cuentas_DepositoTerceros.getSelectedItem();
        int monto = Integer.parseInt(TF_Monto_DepositoTerceros.getText());
        cuenta.setSaldoDisponible(cuenta.getSaldoDisponible() + monto);
  
        Transaccion nTrans = new Transaccion(cuenta.getNumCuenta(), "Deposito a terceros de L." + monto + ", cliente: " + clienteActual.getId() , LocalDateTime.now(), idTxn);
        transRecibo = nTrans;
        
        Cliente clienteDeposito = null;
        for (Usuario usuario : usuarios) {
            if (cuenta.getIdCliente().equals(usuario.getId())) {
                clienteDeposito = (Cliente) usuario;
            }
        }
        
        clienteDeposito.getTransacciones().add(nTrans);
        guardarUsuarios(usuarios);
        
        guardarLog("Deposito a terceros, cuenta: " + cuenta.getNumCuenta() + ", monto: L." + monto + ", cliente: " + clienteActual.getId());
        
        JOptionPane.showMessageDialog(D_DepositoTerceros, "Deposito exitoso");
        
        D_DepositoTerceros.setVisible(false);
    }//GEN-LAST:event_B_Depositar_DepositoTercerosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Asignar_AsignarATMs;
    private javax.swing.JButton B_Confirmar_Confirmacion;
    private javax.swing.JButton B_CrearATM_CrearATMs;
    private javax.swing.JButton B_CrearUsuario;
    private javax.swing.JButton B_Depositar_DepositarPropia;
    private javax.swing.JButton B_Depositar_DepositoTerceros;
    private javax.swing.JButton B_DepositoPropias;
    private javax.swing.JButton B_DepositoTerceros;
    private javax.swing.JButton B_EscojerATM;
    private javax.swing.JButton B_EstadoCuenta;
    private javax.swing.JButton B_Finalizar_Mantenimiento;
    private javax.swing.JButton B_IniciarSesion_LogIn;
    private javax.swing.JButton B_NuevaCuenta;
    private javax.swing.JButton B_Retirar_RetiroPropia;
    private javax.swing.JButton B_RetiroPropias;
    private javax.swing.JButton B_RevisarEstado_EstadoCuenta;
    private javax.swing.JButton B_Salir_Transacciones;
    private javax.swing.JButton B_Transacciones;
    private javax.swing.JComboBox<ATM> CB_ATMs_AsignarATMs;
    private javax.swing.JComboBox<ATM> CB_ATMs_InicioSesion;
    private javax.swing.JComboBox<Cuenta> CB_Cuentas_DepositoPropia;
    private javax.swing.JComboBox<Cuenta> CB_Cuentas_DepositoTerceros;
    private javax.swing.JComboBox<Cuenta> CB_Cuentas_EstadoCuenta;
    private javax.swing.JComboBox<Cuenta> CB_Cuentas_RetiroPropia;
    private javax.swing.JComboBox<String> CB_TipoUsuario_CrearUsuario;
    private javax.swing.JComboBox<UsuarioMantenimiento> CB_UsuarioMantenimiento_AsignarATMs;
    private javax.swing.JDialog D_Confirmacion;
    private javax.swing.JDialog D_DepositoPropias;
    private javax.swing.JDialog D_DepositoTerceros;
    private javax.swing.JDialog D_EstadoCuenta;
    private javax.swing.JDialog D_LogIn;
    private javax.swing.JDialog D_MenuCliente;
    private javax.swing.JDialog D_MenuMantenimiento;
    private javax.swing.JDialog D_NuevaCuenta;
    private javax.swing.JDialog D_RetiroPropias;
    private javax.swing.JDialog D_Transacciones;
    private javax.swing.JLabel LBL_Bienvenida_LogIn;
    private javax.swing.JLabel LBL_Pass_Confirmacion;
    private javax.swing.JPasswordField PF_Clave_Confirmacion;
    private javax.swing.JPasswordField PF_Clave_CrearUsuario;
    private javax.swing.JPasswordField PF_Clave_LogIn;
    private javax.swing.JPanel P_ATM;
    private javax.swing.JPanel P_AsignarATMs;
    private javax.swing.JPanel P_InicioSesion;
    private javax.swing.JPanel P_MenuCliente;
    private javax.swing.JPanel P_Usuario;
    private javax.swing.JTable TBL_Transacciones;
    private javax.swing.JTextField TF_Afiliacion_CrearUsuario;
    private javax.swing.JTextField TF_Apellido1_CrearUsuario;
    private javax.swing.JTextField TF_Apellido2_CrearUsuario;
    private javax.swing.JTextField TF_Billetes100_CrearATM;
    private javax.swing.JTextField TF_Billetes100_Mantenimiento;
    private javax.swing.JTextField TF_Billetes500_CrearATM;
    private javax.swing.JTextField TF_Billetes500_Mantenimiento;
    private javax.swing.JTextField TF_Fabricacion_CrearATM;
    private javax.swing.JTextField TF_ID_CrearATM;
    private javax.swing.JTextField TF_ID_CrearUsuario;
    private javax.swing.JTextField TF_ID_LogIn;
    private javax.swing.JTextField TF_Mantenimiento_CrearATM;
    private javax.swing.JTextField TF_Monto_DepositarPropia;
    private javax.swing.JTextField TF_Monto_DepositoTerceros;
    private javax.swing.JTextField TF_Monto_RetiroPropia;
    private javax.swing.JTextField TF_Nacimiento_CrearUsuario;
    private javax.swing.JTextField TF_Nombre1_CrearUsuario;
    private javax.swing.JTextField TF_Nombre2_CrearUsuario;
    private javax.swing.JTextField TF_Ubicacion_CrearATM;
    private javax.swing.JTabbedPane TP_Principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    //Numero de cuenta
    private static int ultNumCuenta;
    
    //Usuarios
    private static ArrayList<Usuario> usuarios = new ArrayList<>();
    
    private static Cliente clienteActual;
    private static UsuarioMantenimiento mantenimientoActual;
    
    //ATM
    private static ArrayList<ATM> atms = new ArrayList<>();
    private static ATM atmActual;
    
    //TRANSACCIONES
    private static int idTxn;
    
    //MISCELANEO
    private static int contador;
    private static Transaccion transRecibo;
    
    //Datos Usuarios
    public static int guardarUsuarios(ArrayList<Usuario> usuarios) {
        int count = 0;
        try(ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("Usuarios"))) {
            for (Usuario usuario : usuarios) {
                os.writeObject(usuario);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return count;
    }
     
    public static int leerUsuarios (ArrayList<Usuario> usuarios) {
        int count = 0;
        try (ObjectInputStream oi = new ObjectInputStream(new FileInputStream("Usuarios"))) {
            while(true) {
                Usuario usuario = (Usuario) oi.readObject();
                usuarios.add(usuario);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } 
        
        return count;
    }
    
    //Datos ATM
    
    public static int guardarATMs(ArrayList<ATM> atms) {
        int count = 0;
        try(ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("ATMs"))) {
            for (ATM atm : atms) {
                os.writeObject(atm);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return count;
    }
    
    public static int leerATMs (ArrayList<ATM> atms) {
        int count = 0;
        try (ObjectInputStream oi = new ObjectInputStream(new FileInputStream("ATMs"))) {
            while(true) {
                ATM atm = (ATM) oi.readObject();
                atms.add(atm);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } 
        
        return count;
    }
    
    public static void guardarLog (String linea) {
        LocalDateTime fechaHora = LocalDateTime.now();
        String ldt = fechaHora.toString().replace("T", " ").substring(0,19);
        try(FileWriter fw = new FileWriter("Log" + ldt + ".txt",true)) {
            
            fw.write(ldt + ": " + linea + "\n");
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void guardarIdTxn(int idTxn) {
        try (FileWriter fw = new FileWriter("IDTXN.txt")) {
            String l = "" + idTxn;
            fw.write (l);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public static int leerIdTxn() {
        int idTxn = 0;
        try (BufferedReader br = new BufferedReader(new FileReader("IDTXN.txt"))) {
            String linea;
            linea = br.readLine();
            idTxn = Integer.parseInt(linea);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return idTxn;
    }
    
    public static void guardarNumCuenta(int numCuenta) {
        try (FileWriter fw = new FileWriter("numCuenta.txt")) {
            String l = "" + numCuenta;
            fw.write (l);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public static int leerNumCuenta() {
        int numCuenta = 0;
        try (BufferedReader br = new BufferedReader(new FileReader("numCuenta.txt"))) {
            String linea;
            linea = br.readLine();
            numCuenta = Integer.parseInt(linea);
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return numCuenta;
    }
}
