/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2.davidbendeck;

import Usuarios.Cliente;
import Usuarios.Usuario;
import Usuarios.UsuarioMantenimiento;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author davidbendeck
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TP_Principal = new javax.swing.JTabbedPane();
        P_InicioSesion = new javax.swing.JPanel();
        P_Usuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TF_ID_CrearUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TF_Nombre1_CrearUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_Nombre2_CrearUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_Apellido1_CrearUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TF_Apellido2_CrearUsuario = new javax.swing.JTextField();
        PF_Clave_CrearUsuario = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TF_Nacimiento_CrearUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TF_Afiliacion_CrearUsuario = new javax.swing.JTextField();
        B_CrearUsuario = new javax.swing.JButton();
        CB_TipoUsuario_CrearUsuario = new javax.swing.JComboBox<>();
        P_ATM = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TF_ID_CrearATM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TF_Ubicacion_CrearATM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TF_Fabricacion_CrearATM = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TF_Mantenimiento_CrearATM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_Billetes100_CrearATM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TF_Billetes500_CrearATM = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        P_AsignarATMs = new javax.swing.JPanel();
        CB_ATMs_AsignarATMs = new javax.swing.JComboBox<>();
        B_Asignar_AsignarATMs = new javax.swing.JButton();
        CB_UsuarioMantenimiento_AsignarATMs = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout P_InicioSesionLayout = new javax.swing.GroupLayout(P_InicioSesion);
        P_InicioSesion.setLayout(P_InicioSesionLayout);
        P_InicioSesionLayout.setHorizontalGroup(
            P_InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        P_InicioSesionLayout.setVerticalGroup(
            P_InicioSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        TP_Principal.addTab("Inicio de Sesión", P_InicioSesion);

        jLabel1.setText("ID:");

        jLabel2.setText("Primer nombre");

        jLabel3.setText("Segundo nombre");

        jLabel4.setText("Primer apellido");

        jLabel5.setText("Segundo apellido");

        jLabel6.setText("Clave");

        jLabel7.setText("Año de nacimiento");

        jLabel8.setText("Año de afiliación");

        B_CrearUsuario.setText("Crear Usuario");
        B_CrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_CrearUsuarioMouseClicked(evt);
            }
        });

        CB_TipoUsuario_CrearUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario Cliente", "Usuario Mantenimiento" }));

        javax.swing.GroupLayout P_UsuarioLayout = new javax.swing.GroupLayout(P_Usuario);
        P_Usuario.setLayout(P_UsuarioLayout);
        P_UsuarioLayout.setHorizontalGroup(
            P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_UsuarioLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(56, 56, 56)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PF_Clave_CrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(TF_Apellido1_CrearUsuario)
                    .addComponent(TF_Apellido2_CrearUsuario)
                    .addComponent(TF_Nacimiento_CrearUsuario)
                    .addComponent(TF_Afiliacion_CrearUsuario)
                    .addComponent(TF_Nombre1_CrearUsuario)
                    .addComponent(TF_Nombre2_CrearUsuario)
                    .addComponent(TF_ID_CrearUsuario))
                .addGap(90, 90, 90)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_CrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CB_TipoUsuario_CrearUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        P_UsuarioLayout.setVerticalGroup(
            P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_UsuarioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_ID_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_UsuarioLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TF_Nombre1_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_UsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_TipoUsuario_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_Nombre2_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_UsuarioLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TF_Apellido1_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TF_Apellido2_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(P_UsuarioLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(B_CrearUsuario)))
                .addGap(27, 27, 27)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PF_Clave_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TF_Nacimiento_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(P_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TF_Afiliacion_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Crear Usuario", P_Usuario);

        jLabel9.setText("ID");

        jLabel10.setText("Ubicacion");

        jLabel11.setText("Año de fabricación");

        jLabel12.setText("Periodo entre mantenimientos (dias)");

        jLabel14.setText("Billetes de 100");

        jLabel13.setText("Billetes de 500");

        jButton1.setText("Crear ATM");

        javax.swing.GroupLayout P_ATMLayout = new javax.swing.GroupLayout(P_ATM);
        P_ATM.setLayout(P_ATMLayout);
        P_ATMLayout.setHorizontalGroup(
            P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ATMLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ATMLayout.createSequentialGroup()
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(P_ATMLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(TF_Mantenimiento_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, P_ATMLayout.createSequentialGroup()
                                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(103, 103, 103)
                                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Billetes100_CrearATM)
                                    .addComponent(TF_Billetes500_CrearATM))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(P_ATMLayout.createSequentialGroup()
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(74, 74, 74)
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_ID_CrearATM, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                            .addComponent(TF_Ubicacion_CrearATM)
                            .addComponent(TF_Fabricacion_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(106, 106, 106))))
        );
        P_ATMLayout.setVerticalGroup(
            P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_ATMLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TF_ID_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TF_Ubicacion_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_ATMLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TF_Fabricacion_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_ATMLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25)))
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TF_Mantenimiento_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TF_Billetes100_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(P_ATMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TF_Billetes500_CrearATM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Crear ATM", P_ATM);

        B_Asignar_AsignarATMs.setText("Asignar ");

        jLabel15.setText("ATM");

        jLabel16.setText("Asignar a");

        jLabel17.setText("------>");

        jLabel18.setText("Usuario de Mantenimiento");

        javax.swing.GroupLayout P_AsignarATMsLayout = new javax.swing.GroupLayout(P_AsignarATMs);
        P_AsignarATMs.setLayout(P_AsignarATMsLayout);
        P_AsignarATMsLayout.setHorizontalGroup(
            P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(253, 253, 253)
                        .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                                .addComponent(jLabel18))))
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addComponent(CB_ATMs_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CB_UsuarioMantenimiento_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(B_Asignar_AsignarATMs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P_AsignarATMsLayout.setVerticalGroup(
            P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18)))
                    .addGroup(P_AsignarATMsLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P_AsignarATMsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CB_ATMs_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_UsuarioMantenimiento_AsignarATMs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addComponent(B_Asignar_AsignarATMs)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        TP_Principal.addTab("Asignar ATMs", P_AsignarATMs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_Principal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TP_Principal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_CrearUsuarioMouseClicked
        // TODO add your handling code here:
        
        String ID = TF_ID_CrearUsuario.getText();
        String nombre1 = TF_Nombre1_CrearUsuario.getText();
        String nombre2 = TF_Nombre2_CrearUsuario.getText();
        String apellido1 = TF_Apellido1_CrearUsuario.getText();
        String apellido2 = TF_Apellido2_CrearUsuario.getText();
        String clave = PF_Clave_CrearUsuario.getText();
        int nacimiento = Integer.parseInt(TF_Nacimiento_CrearUsuario.getText());
        int afiliacion = Integer.parseInt(TF_Afiliacion_CrearUsuario.getText());
        
        for (Usuario usuario : usuarios) {
            if (usuario.getId().equals(ID)) {
                JOptionPane.showMessageDialog(this, "Este ID ya existe");
                return;
            }
        }
        
        String tipoUsuario = (String) CB_TipoUsuario_CrearUsuario.getSelectedItem();
        if (tipoUsuario.equals("Usuario Cliente")) {
            usuarios.add(new Cliente(new ArrayList<Cuenta>(), new ArrayList<Transaccion>(), ID, nombre1, nombre2, apellido1, apellido2, clave, nacimiento, afiliacion));
        } else {
            usuarios.add(new UsuarioMantenimiento(new ArrayList<ATM>(), ID, nombre1, nombre2, apellido1, apellido2, clave, nacimiento, afiliacion));
        }
        
        guardarUsuarios(usuarios);
        JOptionPane.showMessageDialog(this, "Se ha creado un nuevo usuario con exito");
    }//GEN-LAST:event_B_CrearUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Asignar_AsignarATMs;
    private javax.swing.JButton B_CrearUsuario;
    private javax.swing.JComboBox<ATM> CB_ATMs_AsignarATMs;
    private javax.swing.JComboBox<String> CB_TipoUsuario_CrearUsuario;
    private javax.swing.JComboBox<UsuarioMantenimiento> CB_UsuarioMantenimiento_AsignarATMs;
    private javax.swing.JPasswordField PF_Clave_CrearUsuario;
    private javax.swing.JPanel P_ATM;
    private javax.swing.JPanel P_AsignarATMs;
    private javax.swing.JPanel P_InicioSesion;
    private javax.swing.JPanel P_Usuario;
    private javax.swing.JTextField TF_Afiliacion_CrearUsuario;
    private javax.swing.JTextField TF_Apellido1_CrearUsuario;
    private javax.swing.JTextField TF_Apellido2_CrearUsuario;
    private javax.swing.JTextField TF_Billetes100_CrearATM;
    private javax.swing.JTextField TF_Billetes500_CrearATM;
    private javax.swing.JTextField TF_Fabricacion_CrearATM;
    private javax.swing.JTextField TF_ID_CrearATM;
    private javax.swing.JTextField TF_ID_CrearUsuario;
    private javax.swing.JTextField TF_Mantenimiento_CrearATM;
    private javax.swing.JTextField TF_Nacimiento_CrearUsuario;
    private javax.swing.JTextField TF_Nombre1_CrearUsuario;
    private javax.swing.JTextField TF_Nombre2_CrearUsuario;
    private javax.swing.JTextField TF_Ubicacion_CrearATM;
    private javax.swing.JTabbedPane TP_Principal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    
    //Usuarios
    private static ArrayList<Usuario> usuarios = new ArrayList<>();
    
    private static Cliente clienteActual;
    private static UsuarioMantenimiento mantenimientoActual;
    
    //ATM
    private static ArrayList<ATM> atms = new ArrayList<>();
    
    //TRANSACCIONES
    private static int idTxn;
    
    //Datos Usuarios
    public static int guardarUsuarios(ArrayList<Usuario> usuarios) {
        int count = 0;
        try(ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("Usuarios"))) {
            for (Usuario usuario : usuarios) {
                os.writeObject(usuario);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return count;
    }
     
    public static int leerUsuarios (ArrayList<Usuario> usuarios) {
        int count = 0;
        try (ObjectInputStream oi = new ObjectInputStream(new FileInputStream("Usuarios"))) {
            while(true) {
                Usuario usuario = (Usuario) oi.readObject();
                usuarios.add(usuario);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } 
        
        return count;
    }
    
    //Datos ATM
    
    public static int guardarATMs(ArrayList<ATM> atms) {
        int count = 0;
        try(ObjectOutputStream os = new ObjectOutputStream(new FileOutputStream("ATMs"))) {
            for (ATM atm : atms) {
                os.writeObject(atm);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return count;
    }
    
    public static int leerATMs (ArrayList<ATM> atms) {
        int count = 0;
        try (ObjectInputStream oi = new ObjectInputStream(new FileInputStream("ATMs"))) {
            while(true) {
                ATM atm = (ATM) oi.readObject();
                atms.add(atm);
                count++;
            }
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } 
        
        return count;
    }
    
    public static void guardarLog (String linea) {
        try(FileWriter fw = new FileWriter("Log.txt",true)) {
            LocalDateTime fechaHora = LocalDateTime.now();
            fw.write(fechaHora.toString() + ": " + linea);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void guardarIdTxn(int idTxn) {
        try (FileWriter fw = new FileWriter("IDTXN.txt")) {
            String l = "" + idTxn;
            fw.write (l);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
